### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by GreatGreatGreg** [nikoloss/rose-dewdrop#1]
很棒。
core.py中说 ctx.set 无set属性
# ctx.set(zmq.MAX_SOCKETS, 1000000)

一切运行正常，感谢

**Comment by nikoloss** [comment]
您pyzmq使用的哪个版本？我使用的0mq的版本和pyzmq绑定的版本分别如下

> > > zmq.zmq_version()
> > > '4.1.2'
> > > zmq.**version**
> > > '14.7.0'
> > > 是有这个方法的
> > > ctx=zmq.Context()
> > > ctx.set
> > > <built-in method set of Context object at 0x102d3a0c8>

**Comment by GreatGreatGreg** [comment]
确实是版本问题，更新到了最新版本就搞定了。架构很不错。非常感谢
